### ISSUE TITLE
Bluemix default shared domain

### ISSUE THREAD

**Issue by 7ML0** [ibm-cloud-docs/cloud-foundry-public#10]
Hi - quick question. Given the ongoing deprecation of all things 'bluemix' in favour of 'ibm.cloud', is the default shared domain going to change at some point? Will that domain be "deprecated" too? What will the impact on existing apps that are in that domain?
Thanks in advance :)

**Comment by vanadiscrawford** [comment]
Please forgive the significant delay in the response.  Currently the CLI continues to use `mybluemix.net`.  If you are using the console, the default is `cf.appdomain.cloud`.  If at some point that changes, we will be updating the product documentation accordingly.
