### ISSUE TITLE
Document how to use the internal domain name apps.internal

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/cloud-foundry-public#14]
The existence of the internal domain name *apps.internal* should be documented and the documentation should explain how to use it. It should mention how we use for *container to container networking*.

```
Invoking 'cf domains'...

Getting domains in org cloud-europe as...
name                       status   type   details
eu-de.mybluemix.net        shared
eu-de.cf.appdomain.cloud   shared
apps.internal              shared          internal
```

**Comment by higbyk** [comment]
Could you possibly explain what it means that it's "internal"?

I'm trying to create my Node-Red app on IBM Cloud studio and I selected the URL "apps.internal" but it fails to resolve the name. However, if I switch to "mybluemix.net" it works just fine.

There's no indication that either of these URLs should operate differently, so why does "apps.internal" fail?

**Comment by lionelmace** [comment]
@higbyk Internal means a route using this domain is not accessible from public internet. That's why you need to use mybluemix.net for your app.

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
