### ISSUE TITLE
Are we still promoting 30 day free trial?

### ISSUE THREAD

**Issue by RiyaMRoy04** [ibm-cloud-docs/cloud-foundry-public#19]
Are we still promoting 30 day free trial or is it a glitch in the documentation? 
![IMG_5101](https://user-images.githubusercontent.com/11567379/65895738-90df5d80-e3c9-11e9-98cb-96681a4b9dbd.PNG) https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-getting-started

**Comment by vanadiscrawford** [comment]
The 30-day free trial information is no longer in the documentation.
