### ISSUE TITLE
How do you enforce https for python buildpack?

### ISSUE THREAD

**Issue by barvhaim** [ibm-cloud-docs/cloud-foundry-public#28]

**Comment by helloranahi** [comment]
Here is the total map of Bangladesh shown and this map can be used to get from one place to another inside Bangladesh.

**Comment by barvhaim** [comment]
> Here is the total map of Bangladesh shown and this map can be used to get from one place to another inside Bangladesh.

🤔

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
