### ISSUE TITLE
Need to add another option to solve 'Org's memory limit is exceeded' problem.

### ISSUE THREAD

**Issue by IgnazioT** [ibm-cloud-docs/cloud-foundry-public#32]
When customer deploys an app to IBM Cloud and the following error message is displayed:
"FAILED Server error, status code: 400, error code: 100005, message: You have exceeded your organization's memory limit."
He can either increase the memory quota of your account, or reduce the memory that your apps use.
This is explained at the following URL:  https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-ts-cf-apps#ts_outofmemory
There is another possibility to solve that problem that is not documented.
Customer can run the following command to know current org assigned quota

> bx cf org <ORG_Name>

The bx cf quotas command lists the allowed values 

If you do that they can see the org quota - which is one of these values:
> $ bx cf quotas
Invoking 'cf quotas'...

Sometimes, customer can change the quota assigned to the org using the following command: 

> bx cf set-quota

If customer is not authorized to run the last command, then he can contact IBM Support Team asking to the Billing team to make that change.

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
