### ISSUE TITLE
Why are there still sdk_for_nodejs references in the doc?

### ISSUE THREAD

**Issue by patmc2go** [ibm-cloud-docs/cloud-foundry-public#33]
Triggered by this page: 
> https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-node-js-buildpacks

Which might be the only doc page (stil

### UI Issue with same references

https://cloud.ibm.com/catalog/starters/cloud-foundry?runtime=sdk-for-nodejs
![image](https://user-images.githubusercontent.com/12019963/133643829-ce001b0a-be76-44a7-b683-12234a8137d1.png)

![image](https://user-images.githubusercontent.com/12019963/133644075-88ced98e-4801-445f-b529-3ee964885964.png)

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
