### ISSUE TITLE
Information about Cloud Foundry limits in an Enterprise Account

### ISSUE THREAD

**Issue by IBM-SkillsAcademy** [ibm-cloud-docs/cloud-foundry-public#34]
I cannot find information about the Cloud Foundry limits for organizations and spaces under a single Enterprise Account.
For example, what's the maximum number of CF Orgs that can be created? What the maximum number of spaces per Org.
Similar to this information for [IBM Cloud IAM limits](https://cloud.ibm.com/docs/account?topic=account-known-issues#iam_limits) https://cloud.ibm.com/docs/account?topic=account-known-issues#iam_limits

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
