### ISSUE TITLE
Dead Link -- Monitoring Cloud Foundry metrics

### ISSUE THREAD

**Issue by dbreitling** [ibm-cloud-docs/cloud-foundry-public#35]
links to find more information on monitoring CF apps all lead to a dead link
https://cloud.ibm.com/docs/Monitoring-with-Sysdig?topic=Monitoring-with-Sysdig-monitor-cf-sysdig

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
