### ISSUE TITLE
Need v3.67 release notes

### ISSUE THREAD

**Issue by patmc2go** [ibm-cloud-docs/cloud-foundry-public#36]
This is now the default liberty buildpack: liberty-for-java_v3_67-20220303-1119

The release notes are missing (and we already have a ticket). 
> https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-cloud-foundry-public-release-notes

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
