### ISSUE TITLE
Cloud foundry public IP list is not right.

### ISSUE THREAD

**Issue by immi5556** [ibm-cloud-docs/cloud-foundry-public#37]
Hi,

our cloud foundry hosted app's public network ip has to be white listed, which is depending on this document link below.

https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-network-address

and the list of IPs are in below screenshot. 

![image](https://user-images.githubusercontent.com/16042057/169535838-d0e500b3-9935-45e0-94b6-9412a545124e.png)

but the service is not accessible since, the IP seems different.

![image](https://user-images.githubusercontent.com/16042057/169536028-fc4ce5d9-d2f8-479a-a824-a60e192027cf.png)
 
the irony is, the document is also updated recently.

![image](https://user-images.githubusercontent.com/16042057/169536231-3a1cbbf2-3787-480a-b0d4-54399d25d580.png)

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
