### ISSUE TITLE
Broken link "Latest updates to the Node.js buildpack"

### ISSUE THREAD

**Issue by prempiyush** [ibm-cloud-docs/cloud-foundry-public#38]
This [page](https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-available_versions)  has a broken link [Latest updates to the Node.js buildpack](https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-nodejs-latest_updates)

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
