### ISSUE TITLE
Broken Link in logging page

### ISSUE THREAD

**Issue by frykshon** [ibm-cloud-docs/cloud-foundry-public#39]
Problem Page:
https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-monitoring_logging_cloud_foundry_apps

Currently the text reads:

"For more information about log formats and how to view logs, see [Collecting and analyzing logs from IBM Cloud Foundry resources](https://cloud.ibm.com/docs/Log-Analysis-with-LogDNA?topic=Log-Analysis-with-LogDNA-monitor_cfapp_logs)."

Currently it links to:
https://cloud.ibm.com/docs/Log-Analysis-with-LogDNA?topic=Log-Analysis-with-LogDNA-monitor_cfapp_logs

This should link to here instead:
https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-monitor_cfapp_logs

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
