### ISSUE TITLE
Info in the "Logging and Monitoring" page are not updated 

### ISSUE THREAD

**Issue by emiliamato12** [ibm-cloud-docs/cloud-foundry-public#40]
Hello Team, by going here https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-monitoring_logging_cloud_foundry_apps some hyperlinks don't work properly, they redirect to pages where it is shown the following error message: 
<img width="766" alt="image" src="https://user-images.githubusercontent.com/98525517/179727075-1f1caf4e-610a-43c2-bb03-2aef90388a3e.png">

Hyperlink that don't work are:
1. see [Collecting and analyzing logs from IBM Cloud Foundry resources](https://cloud.ibm.com/docs/Log-Analysis-with-LogDNA?topic=Log-Analysis-with-LogDNA-monitor_cfapp_logs) 
2. To retain logs for a longer period and advanced analysis, services like [Object Storage](https://cloud.ibm.com/docs/Log-Analysis-with-LogDNA?topic=Log-Analysis-with-LogDNA-archiving) can be used.
3. For more information about how to monitor IBM Cloud Foundry apps, see [Monitoring Cloud Foundry metrics](https://cloud.ibm.com/docs/Monitoring-with-Sysdig?topic=Monitoring-with-Sysdig-monitor-cf-sysdig).
4. IBM Cloud Foundry apps can configure and expose metrics that can be monitored using IBM Cloud® Monitoring. For more information, see [Monitoring Cloud Foundry metrics](https://cloud.ibm.com/docs/Monitoring-with-Sysdig?topic=Monitoring-with-Sysdig-monitor-cf-sysdig).

Could you please fix it? Thank you.

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
