### ISSUE TITLE
Typo in "Implementation and operational comparison" Table for CF Migration Options

### ISSUE THREAD

**Issue by malec** [ibm-cloud-docs/cloud-foundry-public#41]
Responsibilities is misspelled as "Responsibilites" in table one, last row, second column.

https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-deprecation_option_comparison#cf_depop1

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
