### ISSUE TITLE
Invalid CLI commands in "Creating certificate signing requests"

### ISSUE THREAD

**Issue by rwd** [ibm-cloud-docs/cloud-foundry-public#43]
Page: https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-ssl_csr#ssl_cert_custom_domain

This refers to two CLI commands which as of the latest available version, v2.10.0, do not exist:
* `ibmcloud account domain-cert-map`
* `ibmcloud account domain-cert-unmap`

```
$ ibmcloud --version
ibmcloud version 2.10.0+e37e09e-2022-08-24T17:31:27+00:00

$ ibmcloud account --help | grep domain
  domain-cert                         List certificate info for the specified domain
  domain-cert-add                     Add certificate to the specified domain in an organization
  domain-cert-remove                  Remove certificate from the specified domain in an organization
```

It appears that the only way to map Cloud Foundry certificates to secrets in a Secrets Manager service is to use the web UI.

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
