### ISSUE TITLE
Please add two IP's in washington DC region 

### ISSUE THREAD

**Issue by sivamtkr1102** [ibm-cloud-docs/cloud-foundry-public#46]
For the document https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-network-address , please add the below two IP's in Washington DC (us-east) region section:

150.239.115.228
150.239.85.233

As when we try to resolve the customer domain its resolving with those IP's and client need that document to be updated:
==========================

nslookup saac-prod-east.us-east.mybluemix.net
Server:		172.31.255.241
Address:	172.31.255.241#53

Non-authoritative answer:
saac-prod-east.us-east.mybluemix.net	canonical name = d2de175a-us-east.lb.appdomain.cloud.
Name:	d2de175a-us-east.lb.appdomain.cloud
Address: 150.239.85.233
Name:	d2de175a-us-east.lb.appdomain.cloud
Address: 150.239.115.228

also resolving below domain resolves the same:

nslookup anything-at-all.us-east.cf.appdomain.cloud
Server:		172.31.255.241
Address:	172.31.255.241#53

Non-authoritative answer:
anything-at-all.us-east.cf.appdomain.cloud	canonical name = d2de175a-us-east.lb.appdomain.cloud.
Name:	d2de175a-us-east.lb.appdomain.cloud
Address: 150.239.115.228
Name:	d2de175a-us-east.lb.appdomain.cloud
Address: 150.239.85.233

**Comment by andrew-edgar** [comment]
You are using the page incorrectly.  This list of IPs is the list where the applications are running and can initiate calls from.   So the backend IPs of the applications.

This never was meant to show the ingress IPs.

**Comment by andrew-edgar** [comment]
The IPs you are resolving to are a DNS entry 

custom-domain.us-east.cf.cloud.ibm.com

And is documented here ...

https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-custom-domains&mhsrc=ibmsearch_a&mhq=custom+domain

in case you are using a custom domain or will always be resolved using the DNS lookup you mentioned in the issue.

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
