### ISSUE TITLE
Hyperlinks in the Logging and Monitoring CF page are not clickable 

### ISSUE THREAD

**Issue by emiliamato12** [ibm-cloud-docs/cloud-foundry-public#47]
Hello Team, 
the hyperlinks provided at this page https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-monitoring_logging_cloud_foundry_apps are not clickable, for each of them I'm being redirected to a page in the IBM Cloud docs showing the following error message 
***
Sorry, this content isn’t available.
It seems we can’t find what you’re looking for. Try the IBM Cloud Docs search to find information.
***

The links that are not clickable are:
1. [Collecting and analyzing logs from IBM Cloud Foundry resources](https://cloud.ibm.com/docs/Log-Analysis-with-LogDNA?topic=Log-Analysis-with-LogDNA-monitor_cfapp_logs) 
2. [Object Storage](https://cloud.ibm.com/docs/Log-Analysis-with-LogDNA?topic=Log-Analysis-with-LogDNA-archiving)
3. [Monitoring Cloud Foundry metrics](https://cloud.ibm.com/docs/Monitoring-with-Sysdig?topic=Monitoring-with-Sysdig-monitor-cf-sysdig)
4. [Monitoring Cloud Foundry metrics](https://cloud.ibm.com/docs/Monitoring-with-Sysdig?topic=Monitoring-with-Sysdig-monitor-cf-sysdig)
 
Screenshot attached for your reference
<img width="755" alt="image" src="https://user-images.githubusercontent.com/98525517/232711307-8b5f9647-35f9-482a-a5e3-272281146f0a.png">

Can you please fix this? Thank you.

**Comment by vanadiscrawford** [comment]
Service is deprecated and documentation is being removed. Thank you for your comment.
