### ISSUE TITLE
Infrastructure link invalid

### ISSUE THREAD

**Issue by lyndell** [ibm-cloud-docs/cloud-foundry-public#8]
The [Viewing IBM Cloud infrastructure layers](https://cloud.ibm.com/docs/cf.html#infralayers) link under the [Cloud Foundry architecture in IBM Cloud](https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-howwork#architecture) heading is invalid.  The opened page states: Page Not Found.

**Comment by vanadiscrawford** [comment]
This link has been fixed.  Thank you for raising the issue.
